# name: CI for Add and Subtract App

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Code
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: 18

#     - name: Install Dependencies
#       run: npm install

#     - name: Run Tests
#       run: npm test


name: Node.js CI/CD

on:
  push:
    branches:
      - server
  pull_request:
    branches:
      - server

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test

    - name: Build Docker image
      run: docker build -t simple-node-ci-cd .

    - name: Tag Docker image
      run: docker tag simple-node-ci-cd mubasirvc/simple-node-ci-cd:latest

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push mubasirvc/simple-node-ci-cd:latest
